def COLOR_MAP = [
      'SUCCESS': 'good',
      'FAILURE': 'danger',
]

pipeline {
    agent any   

    environment {
        cluster = 'prod-cluster'
        service = 'service-prod-ecs'
    }

    stages {
        stage('ecs prod deploy') {
            steps {
                withAWS(credentials: 'awscred', region: 'us-east-2') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment' 
                }

            }
        }
    }
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#devops',
               color: COLOR_MAP[currentBuild.currentResult],
               message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More Info At: ${env.BUILD_URL}"
        }
    }

}
